### ISSUE TITLE
Exit with output.tre file, probably due to excessive `N+`

### ISSUE THREAD

**Issue by cbird808** [ariloytynoja/pagan2-msa#1]
I'm aligning full and partial mito genomes, and pagan2 does not produce an aligned output.fasta, but does produce an output.tre file.

Here's an example fasta (had to change suffix to txt) that was created from bam files, and is nearly aligned: [testin.txt](https://github.com/ariloytynoja/pagan2-msa/files/4159435/testin.txt).  

One sequence has a large portion of missing data.

MAFFT will align this, but not as well as pagan2, which is the best aligner I've ever used.  Is there any chance that there is a fix for this?

Here's the termial:

```bash
pagan2 -s testin.fasta -o testout --threads 7

PAGAN2 v.1.53 (29 August, 2019). (C) 2010-2019 by Ari Löytynoja <ari.loytynoja@gmail.com>.
 This program is provided "as-is", with NO WARRANTY whatsoever; this is a development version
 and may contain bugs.

The analysis started: Wed Feb  5 06:17:45 2020

 aligning node #2# (2/4): AP011247.1_Puntioplites_proctozystron_mtGenome - NC_031553.1_Puntioplites_proctozystron_mtGenome.(base)
```

When I remove the sequence with a lot of N, it works fine.

**Comment by ariloytynoja** [comment]
Thanks for reporting this.

I'm not sure what's causing this but I assume that it's related to the NCBI toolkit and the use of Blast via there. That doesn't understand N's and X's and causes some issues elsewhere too.

I have no fix in pagan2 but I can provide a couple of work-arounds. Please experiment with these:

```
less testin.txt | head -8 > good.txt
pagan2 -s good.txt -o good
```

```
less testin.txt | tail -1 | sed 's/N\{20,\}/\n>At_Pfa034\n/g' > bad.txt
pagan2 -a good.fas -r good.tre -q bad.txt -o testout --pileup --build-contigs --output-consensus
```
```
less testin.txt | tail -2 | sed 's/N\{20,\}/NNNNN/g' > bad2.txt
pagan2 -a good.fas -r good.tre -q bad2.txt -o testout2 --pileup --no-terminal-edges
```

```
less testin.txt | sed 's/N\{20,\}/NNNNN/g' > testin3.txt
pagan2 -q testin3.txt -o testout3  --pileup --no-terminal-edges
```

The last one is the least disruptive. You could simply remove long runs of N's in you input and let pagan2 to find the alignment. "--no-terminal-edges" may help.

**Comment by cbird808** [comment]
that was helpful, thank you!

If only the bam alignments that I converted to fasta could be perfectly aligned, but indels seem to cause the minor misalignments in the testin.txt file.
