### ISSUE TITLE
--both-strands Does not seem to help

### ISSUE THREAD

**Issue by vmkalbskopf** [ariloytynoja/pagan2-msa#2]
HI there

I am aligning DNA where the samples are being aligned to a reference to find the reading frame. However some of the samples are from the minus strand. So I thought I could use the --both-strands option so pagan2 can find the optimal solution. But it does not seem to help.

How is that option supposed to work?

**Comment by ariloytynoja** [comment]
Hi,

Please try these commands to see how it works with the demo data:

```
wget https://raw.githubusercontent.com/ariloytynoja/pagan-msa/master/examples/ngs_placement/input_ngs_primates.fas -O - | head -4 > reads.fa

head -2 reads.fa > read1.fa

( tail -n+3 reads.fa | head -1 && tail -1 reads.fa | rev | tr '[ACGT]' '[TGCA]' ) > read2.fa

wget https://raw.githubusercontent.com/ariloytynoja/pagan-msa/master/examples/ngs_placement/human.fas

pagan2 -a human.fas -q <(cat read[12].fa) --noise 2 --one-placement

grep ">" outfile.fas

pagan2 -a human.fas -q <(cat read[12].fa) --noise 2 --one-placement --both-strands

grep ">" outfile.fas
```

Here, `--one-placement-only`  tells to place the sequence to one of the (possibly many) equally good tree positions and `--noise 2` gives debugging information. From the latter, you can interpret if considering the reverse-complement found a better match.

Cheers,

Ari

**Comment by ariloytynoja** [comment]
I assume that the example above explained the functionality and solved the issue.
