### ISSUE TITLE
Computing BppDist guidetree is failed

### ISSUE THREAD

**Issue by keniko90** [ariloytynoja/pagan2-msa#4]
Hi,

I can use pagan without any problem, but in some cases I get this error message:
"Computing BppDist guidetree for the initial alignment.terminate called after throwing an instance of 'bpp::Exception'
  what():  VectorSiteContainer::VectorSiteContainer. Empty site set." 
Could you help me what can be the problem? I have not find any solution so far.

Thank you!

**Comment by ariloytynoja** [comment]
Hi,

If you download the package "pagan2.linux64.20190829.tgz," it should include all the helper utilities. By default, Mafft and  FastTree are used for the guide tree inference. FastTree should provide superior trees, and there's no reason to use BppDist for that.

Best,
Ari
